---
title: "R Notebook"
output: html_notebook
---

```{r}
library(data.table)
library(RcppSimdJson)
library(readxl)
```

Wczytanie danych z KPRM

```{r}
kprm <- readRDS("../data/kprm_df.rds")
head(kprm)
```

Wczytuje dane z dysku

```{r}
zawody1 <- fread("~/git/zbiory/kprm/new-pred/kprm_tra_zawody1.csv", skip = 1)
zawody1[, V1:=NULL]
setnames(zawody1, names(zawody1), paste0("zawod", 1:9))
zawody1$zawod1_kod <- apply(zawody1, 1, which.max)
zawody1$zawod1_prob <- apply(zawody1[,1:9], 1, max)
zawody1[, .N, keyby = zawod1_kod]
colSums(zawody1[, 1:9])
```


Wczytujemy kody 6 cyfrowe

```{r}
zawod6 <- fread("~/git/zbiory/kprm/new-pred/kprm_tra_zawody6.csv", skip = 1)
zawod6[,V1 := NULL]
zawod6
```

```{r}
kody_6_df <- data.frame(id = kprm$id,
                       zawod6_kod1 = zawod6$V2,
                       zawod6_prob1 = zawod6$V7,
                       zawod6_kod2 = zawod6$V3,
                       zawod6_prob2 = zawod6$V8)


kody_6_df <- setDT(kody_6_df)

kody_6_df[, ":="(zawod1_kod=zawody1$zawod1_kod, 
                 zawod1_prob=zawody1$zawod1_prob)]

kody_6_df[, ":="(zawod6_kod1=as.character(zawod6_kod1), 
                 zawod6_kod2=as.character(zawod6_kod2))]


head(kody_6_df)
```
Nazwy zawodów

```{r}
zawody <- readRDS("~/git/nauka/job-offers-classification/data/ksiz-occups-desc-wide.rds")
zawody <- zawody[,1:2]
setnames(zawody, c("zawod", "nazwa"), c("zawod_kod","zawod_nazwa"))
head(zawody)
```

```{r}
kody_zaw <- merge(x = kody_6_df,
                  y = zawody,
                  by.x = "zawod6_kod1",
                  by.y = "zawod_kod",
                  all.x = T)

kody_zaw <- merge(x = kody_zaw,
                  y = zawody,
                  by.x = "zawod6_kod2",
                  by.y = "zawod_kod",
                  all.x = T)

kody_zaw[, zawod1_nazwa := fcase(zawod1_kod == 1, "1.Przedstawiciele władz publicznych, wyżsi urzędnicy i kierownicy",
                                 zawod1_kod == 2, "2.Specjaliści",
                                 zawod1_kod == 3, "3.Technicy i inny średni personel",
                                 zawod1_kod == 4, "4.Pracownicy biurowi", 
                                 zawod1_kod == 5, "5.Pracownicy usług i sprzedawcy",
                                 zawod1_kod == 6, "6.Rolnicy, ogrodnicy, leśnicy i rybacy",
                                 zawod1_kod == 7, "7.Robotnicy przemysłowi i rzemieślnicy",
                                 zawod1_kod == 8, "8.Operatorzy i monterzy maszyn i urządzeń", 
                                 zawod1_kod == 9, "9.Pracownicy wykonujący prace proste")]

kody_zaw <- kody_zaw[, .(id, 
                         zawod1_kod, zawod1_prob, zawod1_nazwa,
                         zawod6_kod1, zawod6_prob1, zawod6_nazwa1 = zawod_nazwa.x,
                         zawod6_kod2, zawod6_prob2, zawod6_nazwa2 = zawod_nazwa.y)]

kody_zaw[, .N, keyby = zawod6_nazwa1][order(-N)]
```

Zapis

```{r}
saveRDS(kody_zaw, file = "../data/kprm_zawody_df.rds")
```




